-- v2.0.0_5 - English Tags

INSERT INTO t_tag (tag, lang_id, text) VALUES
      ('PLAYER_WELCOME', 'en', 'Welcome! I just added you to my database.\nWhen you need help you only have to send me the command /help\nThank you for joining!'),
      ('ALL_MESSAGES_SENT', 'en', 'All messages sent.'),
      ('GO_BACK', 'en', '← Go back'),
      ('ACCEPT', 'en', 'Accept'),
      ('CANCEL', 'en', 'Cancel'),

      ('USER_LANG_CHANGE', 'en', 'Choose your language:'),
      ('USER_LANG_CHANGED', 'en', 'Language changed successfully.'),

      ('DICTIONARIES_HELP', 'en', 'Welcome to the help menu. You are playing {0} version {1}\n\nYou can check the help documentation in this link: {2}\n\nShare your dictionaries!!\n\n\nCreated by {3}.'),
      ('DICTIONARIES_MAIN_MENU', 'en', 'Hi! I´m the bot that will help you creating and managing dictionaries for CCLHBot.\nThis are the actions that you can do:'),
      ('DICTIONARIES_LIST_BUTTON', 'en', 'List my dictionaries'),
      ('DICTIONARIES_CREATE_BUTTON', 'en', 'Create dictionary'),
      ('DICTIONARIES_RENAME_BUTTON', 'en', 'Rename dictionary'),
      ('DICTIONARIES_LANG_BUTTON', 'en', 'Change language'),
      ('DICTIONARIES_DELETE_BUTTON', 'en', 'Delete dictionary'),
      ('DICTIONARIES_TOGGLE_PUBLISH_BUTTON', 'en', 'Publish/unpublish dictionary'),
      ('DICTIONARIES_TOGGLE_SHARE_BUTTON', 'en', 'Share/unshare dictionary'),
      ('DICTIONARIES_MANAGE_CARDS_BUTTON', 'en', 'Manage cards'),
      ('DICTIONARIES_MANAGE_COLLABS_BUTTON', 'en', 'Manage collaborators'),
      ('DICTIONARIES_LIST', 'en', ' These are the dictionaries that you have created or you are collaborator:\n\n{0}'),
      ('DICTIONARIES_RENAME_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to rename.'),
      ('DICTIONARIES_DELETE_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to borrar.'),
      ('DICTIONARIES_CHANGE_LANG_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to change its language'),
      ('DICTIONARIES_TOGGLE_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to publish/unpublish.'),
      ('DICTIONARIES_SHARE_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to share/unshare.'),
      ('DICTIONARIES_MANAGE_CARDS_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to edit its cards.'),
      ('DICTIONARIES_MANAGE_COLLABORATORS_LIST', 'en', 'These are the dictionaries that you have created:\n\n{0}\n\nNow answer me with the id from the dictionary you want to edit its collaborators.'),
      ('DICTIONARY_CREATE', 'en', 'OK! Answer me with the name of the dictionary you want to create.'),
      ('DICTIONARY_CREATED', 'en', 'Your dictionary have been successfully created, no go to the ´Manage cards´ menu to add cards.'),
      ('DICTIONARY_RENAME', 'en', 'OK! Answer me with the new name of the dictionary you want to rename.'),
      ('DICTIONARY_RENAMED', 'en', 'Your dictionary have been successfully renamed.'),
      ('DICTIONARY_CHANGE_LANG', 'en', 'Answer me with the language code you want to choose:\n{0}'),
      ('DICTIONARY_LANG_CHANGED', 'en', 'The language of your dictionary have been successfully changed.'),
      ('DICTIONARY_TOGGLED_ON', 'en', 'You have published the dictionary {0} sucessfully.'),
      ('DICTIONARY_TOGGLED_OFF', 'en', 'You have unpublished the dictionary {0} sucessfully.'),
      ('DICTIONARY_SHARED_ON_REQUEST', 'en', 'You have requested to share dictionary {0}.'),
      ('DICTIONARY_SHARED_OFF_REQUEST', 'en', 'You have requested to unshare dictionary {0}.'),
      ('DICTIONARY_SHARED_ON', 'en', 'You have shared the dictionary {0} sucessfully.'),
      ('DICTIONARY_SHARED_OFF', 'en', 'You have unshared the dictionary {0} sucessfully.'),
      ('DICTIONARY_SHARED_REJECTED', 'en', 'You have rejected to share the dictionary {0}.'),
      ('DICTIONARY_DELETE', 'en', '<b>ATTENTION! This dictionary is PUBLISHED</b>. The dictionary will be deleted and also its <b>cards</b> too.\n\n¿Are you COMPLETELY sure you want to delete it?\n· Answer YES to delete it.\n· Answer anything else or ignore the message to reject.'),
      ('DICTIONARY_DELETED', 'en', 'Your dictionary have been successfully deleted.'),
      ('DICTIONARY_DELETE_CANCELLED', 'en', 'You have cancelled the deletion of the dictionary.'),

      ('CARDS_MENU', 'en', 'You are managing the cards of the dictionary: {0}'),
      ('CARDS_WHITE_LIST_BUTTON', 'en', 'List white cards'),
      ('CARDS_BLACK_LIST_BUTTON', 'en', 'List black cards'),
      ('CARDS_WHITE_ADD_BUTTON', 'en', 'Add white cards'),
      ('CARDS_BLACK_ADD_BUTTON', 'en', 'Add black cards'),
      ('CARDS_WHITE_EDIT_BUTTON', 'en', 'Edit white card'),
      ('CARDS_BLACK_EDIT_BUTTON', 'en', 'Edit black card'),
      ('CARDS_WHITE_REMOVE_BUTTON', 'en', 'Delete white card'),
      ('CARDS_BLACK_REMOVE_BUTTON', 'en', 'Delete black card'),
      ('CARDS_WHITE_LIST', 'en', 'On my way! There are the white cards. (It´s possible that they´re send in multiple messages)'),
      ('CARDS_WHITE_LIST_END', 'en', 'These are all the white cards.'),
      ('CARDS_WHITE_CARD_ADD', 'en', 'Answer me with the text of the white card you want to add.'),
      ('CARDS_WHITE_CARD_ADD_ANOTHER', 'en', 'Answer me with the text of the white card you want to add or type :cancel: to go back to the menu.'),
      ('CARDS_WHITE_CARD_ADDED', 'en', 'White card added successfully. You have {0} out of {1}.'),
      ('CARDS_WHITE_CARD_EDIT', 'en', 'Answer me with the id of the white card you want to edit.'),
      ('CARDS_WHITE_CARD_EDIT_NEW_TEXT', 'en', 'Answer me with the new text you want for that white card.'),
      ('CARDS_WHITE_CARD_EDITED', 'en', 'White card edited successfully.'),
      ('CARDS_WHITE_CARD_DELETE', 'en', 'Answer me with the id of the white card you want to delete.'),
      ('CARDS_WHITE_CARD_DELETED', 'en', 'White card deleted successfully.'),
      ('CARDS_BLACK_LIST', 'en', 'On my way! There are the black cards. (It´s possible that they´re send in multiple messages)'),
      ('CARDS_BLACK_LIST_END', 'en', 'These are all the black cards.'),
      ('CARDS_BLACK_CARD_ADD', 'en', 'Answer me with the text of the black card you want to add.'),
      ('CARDS_BLACK_CARD_ADD_ANOTHER', 'en', 'Answer me with the text of the black card you want to add or type :cancel: to go back to the menu.'),
      ('CARDS_BLACK_CARD_ADDED', 'en', 'Black card added successfully. You have {0} out of {1}.'),
      ('CARDS_BLACK_CARD_EDIT', 'en', 'Answer me with the id of the black card you want to edit.'),
      ('CARDS_BLACK_CARD_EDIT_NEW_TEXT', 'en', 'Answer me with the new text you want for that black card.'),
      ('CARDS_BLACK_CARD_EDITED', 'en', 'Black card edited successfully.'),
      ('CARDS_BLACK_CARD_DELETE', 'en', 'Answer me with the number of the white card you wish to delete.'),
      ('CARDS_BLACK_CARD_DELETED', 'en', 'Black card deleted succesfully.'),

      ('COLLABORATORS_MENU', 'en', 'You´re managing the collaborators of the dictionary: {0}'),
      ('COLLABORATORS_LIST_BUTTON', 'en', 'List collaborators'),
      ('COLLABORATORS_ADD_BUTTON', 'en', 'Add collaborator'),
      ('COLLABORATORS_DELETE_BUTTON', 'en', 'Remove collaborator'),
      ('COLLABORATORS_TOGGLE_BUTTON', 'en', 'Activate/Deactivate collaborator'),
      ('COLLABORATORS_LIST', 'en', 'These are the collaborators of this dictionary:\n\n{0}'),
      ('COLLABORATORS_ADD', 'en', 'Let´s go! Tell me the name (e.g. @cclhbot) or the ID (you can obtain it with the command /getmyid) from the user you want to activate/deactivate as collaborator.\n\n<b>WARNING: The collaborator you want to add must have initiated this bot first (texting /start in private.</b>'),
      ('COLLABORATORS_ADDED', 'en', 'A collaborator invitation has been sent to {0} successfully. You must now accept the invitation.'),
      ('COLLABORATORS_ACCEPT_MESSAGE', 'en', '{0} has invited you to collaborate in their dictionary {1}.'),
      ('COLLABORATORS_ACCEPTED_CREATOR', 'en', '{0} has accepted to be collaborator.'),
      ('COLLABORATORS_REJECTED_CREATOR', 'en', '{0} has rejected to be collaborator.'),
      ('COLLABORATORS_ACCEPTED_MESSAGE', 'en', 'Perfect! You´re already a collaborator, now ask the bot´s creator to activate you.'),
      ('COLLABORATORS_REJECTED_MESSAGE', 'en', 'You has rejected to be a collaborator.'),
      ('COLLABORATORS_DELETE', 'en', 'Let´s go! Tell me the name (e.g. @cclhbot) or the ID (you can obtain it with the command /getmyid) from the user you want to activate/deactivate as collaborator.'),
      ('COLLABORATORS_DELETED', 'en', 'The collaborator has been deleted succesfully.'),
      ('COLLABORATORS_DELETED_MESSAGE', 'en', 'You have been removed from the dictionary {0}'),
      ('COLLABORATORS_TOGGLE', 'en', 'Let´s go! Tell me the name (e.g. @cclhbot) or the ID (you can obtain it with the command /getmyid) from the user you want to activate/deactivate as collaborator.'),
      ('COLLABORATORS_TOGGLED_ON', 'en', 'The collaborator {0} has been toggled on.'),
      ('COLLABORATORS_TOGGLED_OFF', 'en', 'The collaborator {0} has been toggled off.'),
      ('COLLABORATORS_TOGGLED_ON_MESSAGE', 'en', 'You gained editing permissions in the dictionary {0}.'),
      ('COLLABORATORS_TOGGLED_OFF_MESSAGE', 'en', 'You lost editing permissions in the dictionary {0}.'),

      ('GAME_HELP', 'en', 'Welcome to the help menu of {0} version {1}\n\nYou can check for help here: {2}\n\nEnjoy the bot and... Let´s play!\n\nMade by {3}.'),
      ('GAME_CREATING', 'en', 'Hold on, I´m creating the game...'),
      ('GAME_CREATED_GROUP', 'en', 'I already created the game!'),
      ('GAME_SELECT_MODE', 'en', '\nSelect game mode:'),
      ('GAME_PUNCTUATION_MODE', 'en', '\nSelect score mode:'),
      ('GAME_TYPE_ROUNDS_SELECT', 'en', '\nSelect rounds of the game:'),
      ('GAME_TYPE_POINTS_SELECT', 'en', '\nSelect number of points to win:'),
      ('GAME_SELECTED_MODE', 'en', 'The game mode is <b>{0}</b>.'),
      ('GAME_MODE_DEMOCRACY', 'en', 'Democracy'),
      ('GAME_MODE_CLASSIC', 'en', 'Classic'),
      ('GAME_MODE_DICTATORSHIP', 'en', 'Dictatorship'),
      ('GAME_DICTIONARY_SELECT', 'en', '\nSelect dictionary:'),
      ('GAME_SELECTED_DICTIONARY', 'en', 'The dictionary selected is <b>{0}</b>.'),
      ('GAME_TYPE_POINTS', 'en', 'Points'),
      ('GAME_TYPE_ROUNDS', 'en', 'Rounds'),
      ('GAME_SELECTED_POINTS_TO_WIN', 'en', 'The number of points to win is <b>{0}</b>.'),
      ('GAME_SELECTED_ROUNDS_TO_END', 'en', 'The number of rounds is <b>{0}</b>.'),
      ('GAME_SELECT_MAX_PLAYERS', 'en', '\nSelect max number of players:'),
      ('GAME_SELECTED_MAX_PLAYER_NUMBER', 'en', 'The maximum number of players is <b>{0}</b>.'),
      ('GAME_CREATED_CURRENT_PLAYER_NUMBER', 'en', '<b>{0}</b> players have joined:'),
      ('GAME_CREATED_CURRENT_VOTE_DELETION_NUMBER', 'en', '<b>{0}</b> player/s have voted to delete the game.'),
      ('GAME_SELECT_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of this round is <b>{1}</b>\n\nNow the players will play their white cards in private.'),
      ('GAME_VOTE_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of this round is <b>{1}</b>\n\nThe players chose the following white cards: \n\n<b>{2}</b>\n\nNow the players will vote in private.'),
      ('GAME_END_ROUND', 'en', 'Congratulations <b>{0}</b>! Your card <b>{1}</b> has won the round <b>{2}</b>.\n\nThe black card of this round was <b>{3}</b>\n\nThe players chose the following white cards:\n<b>{4}</b>\n\nThe score is the following:\n<b>{5}</b>'),
      ('GAME_END_GAME', 'en', 'Game! The winner is... <b>{0}</b>. Congratulations!!!'),
      ('GAME_DELETED', 'en', 'Game deleted.'),
      ('GAME_DELETION_USER', 'en', '{0}´s game has been deleted.'),
      ('GAME_DELETION_ALL', 'en', 'All games have been deleted.'),
      ('GAME_DELETION_FORCED', 'en', 'Sorry, the game has been deleted by an admin. You can start a new game.'),
      ('GAME_LEAVE', 'en', 'Leave game'),
      ('GAME_LEFT', 'en', 'You left the game.'),
      ('GAME_JOIN_BUTTON', 'en', 'Join game'),
      ('GAME_CONFIGURE_BUTTON', 'en', 'Configure game'),
      ('GAME_START_BUTTON', 'en', 'Start game'),
      ('GAME_DELETE_BUTTON', 'en', 'Delete game'),
      ('GAME_CHANGE_GAME_MODE', 'en', 'Change game mode'),
      ('GAME_CHANGE_PUNCTUATION_MODE', 'en', 'Change punctuation mode.'),
      ('GAME_CHANGE_DICTIONARY', 'en', 'Change dictionary.'),
      ('GAME_CHANGE_MAX_N_PLAYERS', 'en', 'Change number of max players.'),

      ('PLAYER_CREATED_GAME', 'en', 'I created a game in the group, you can configure it there.'),
      ('PLAYER_JOINING', 'en', 'Hold on, you are joining the game...'),
      ('PLAYER_JOINED', 'en', 'You joined the game.'),
      ('PLAYER_SELECT_CARD', 'en', '<b>Ronda {0}</b>\n\nThe black card of this round is:\n\n<b>{1}</b>\n\nYou have to choose a white card of the following:'),
      ('PLAYER_SELECTED_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of the round is:\n\n<b>{1}</b>\n\nYou chose this white card:\n\n<b>{2}</b>'),
      ('PLAYER_VOTE_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of the round is:\n\n<b>{1}</b>\n\nYou chose the white card:\n\n<b>{2}</b>\n\nYou have to vote one of the following cards:'),
      ('PLAYER_VOTED_CARD', 'en', '<b>Round {0}</b>\n\nThe black card of the round is:\n\n<b>{1}</b>\n\nYou chose this white card:\n\n<b>{2}</b>\n\nYou voted the white card:\n\n<b>{3}</b>'),
      ('PLAYER_VOTED_DELETION', 'en', 'You voted to delete the game.'),

      ('ERROR_COMMAND_SHOULD_BE_ON_PRIVATE', 'en', 'This command must be sent privately to the bot.'),
      ('ERROR_COMMAND_SHOULD_BE_ON_GROUP', 'en', 'This command must be sent in a group in which the bot is.'),
      ('ERROR_UNKNOWN', 'en', 'Unknown error.'),
      ('ERROR_USER_ALREADY_REGISTERED', 'en', 'You´re already registered. Write /help for more information.'),
      ('ERROR_DICTIONARY_ALREADY_EXISTS', 'en', 'There is already a dictionary with this name.'),
      ('ERROR_DICTIONARY_NOT_FOUND', 'en', 'This dictionary doesn´t exist.'),
      ('ERROR_DICTIONARY_NOT_YOURS', 'en', 'That dictionary doesn´t belong to you.'),
      ('ERROR_DICTIONARY_NOT_FILLED', 'en', 'You can´t publish the dictionary because due to a lack of cards.'),
      ('ERROR_DICTIONARY_NOT_PUBLISHED', 'en', 'You can´t share a dictionary that it´s no published. Publish it to share it.'),
      ('ERROR_DICTIONARY_ALREADY_FILLED', 'en', 'You can´t add more kind of cards to this dictionary.'),
      ('ERROR_DICTIONARY_ALREADY_PUBLISHED', 'en', 'You can´t edit a dictionary that it´s already published. Unpublish it to edit it.'),
      ('ERROR_DICTIONARY_ALREADY_SHARED', 'en', 'You can´t modify a dictionary that it´s already shared. Contact {0} to unpublish it.'),
      ('ERROR_DICTIONARY_SHARED', 'en', 'The dictionary is shared, contact {0} to delete it.'),
      ('ERROR_COLLABORATOR_DOESNT_EXISTS', 'en', 'The user is incorrect or is not registered on the bot.'),
      ('ERROR_COLLABORATOR_ADD_USER_DOESNT_EXISTS', 'en', 'The user that you´re trying to add as collaborator is incorrect or it´s not registered on the bot.'),
      ('ERROR_COLLABORATOR_REMOVE_USER_DOESNT_EXISTS', 'en', 'The user that you´re trying to delete as collaborator is incorrect or it´s not a collaborator in this dictionary.'),
      ('ERROR_COLLABORATOR_ADD_ALREADY_EXISTS', 'en', 'The user you are trying to add is already a collaborator in this dictionary.'),
      ('ERROR_COLLABORATOR_ADD_MAX_REACHED', 'en', 'You have reached the maximum number of collaborators and you can´t add any more.'),
      ('ERROR_CARD_ALREADY_EXISTS', 'en', 'There already exists a card with the same text in this dictionary.'),
      ('ERROR_CARD_EXCEEDED_LENGTH', 'en', 'The card exceeds the maximum of {0} characters.'),
      ('ERROR_CARD_NOT_YOURS', 'en', 'This card is not yours.'),
      ('ERROR_CARD_DOESNT_EXISTS', 'en', 'The card you´re trying to edit does not exist.'),
      ('ERROR_GAME_ALREADY_CREATED', 'en', 'There is an active game in this group or the creator has an active game on another group.'),
      ('ERROR_GAME_ALREADY_FILLED', 'en', 'The game has already reached the maximum of players.'),
      ('ERROR_GAME_ALREADY_STARTED', 'en', 'The game has already started.'),
      ('ERROR_GAME_ONLY_CREATOR_CAN_CONFIGURE', 'en', 'Only the creator can configure it.'),
      ('ERROR_GAME_ONLY_CREATOR_CAN_DELETE', 'en', 'Only the creator can delete it.'),
      ('ERROR_GAME_ONLY_CREATOR_CAN_START', 'en', 'Only the creator can start the game.'),
      ('ERROR_GAME_DOESNT_EXISTS', 'en', 'There is no game initiated in this group.'),
      ('ERROR_GAME_USER_DOESNT_EXISTS', 'en', 'You are not registered. Input /start in private.'),
      ('ERROR_GAME_NOT_FILLED', 'en', 'The game has not reached the minimum number of players.'),
      ('ERROR_GAME_NOT_STARTED', 'en', 'The game has not started.'),
      ('ERROR_PLAYER_NO_GAMES', 'en', 'You have no active games.'),
      ('ERROR_PLAYER_ALREADY_PLAYING', 'en', 'You are already playing a game.'),
      ('ERROR_PLAYER_ALREADY_JOINED', 'en', 'Ya estas participando en esta partida.'),
      ('ERROR_PLAYER_DOES_NOT_EXISTS', 'en', 'You have not joined any game.'),
      ('ERROR_PLAYER_ALREADY_PLAYED_CARD', 'en', 'You have already played a card.'),
      ('ERROR_PLAYER_ALREADY_VOTED_CARD', 'en', 'You have already voted for a card.'),
      ('ERROR_PLAYER_ALREADY_VOTED_DELETION', 'en', 'You have already voted for a card.'),
      ('ERROR_CANT_FIND_WINNER_CARD', 'en', 'Cannot find winner card.');
